### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1 

### ISSUE THREAD

**Issue by divyenduz** [prisma/quaint#205]
Command: `prisma migrate up --experimental`
Version: `2.9.0`
Binary Version: `369b3694b7edb869fad14827a33ad3f3f49bbc20`
Report: https://prisma-errors.netlify.app/report/11672 
OS: `x64 win32 10.0.18363`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (C:\Users\abdel$\Documents\shopify_back_end\prod\prisma2.0\node_modules\@prisma\cli\build\index.js:412:153)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1
```

**Comment by tomhoule** [comment]
Probably coming from the error message parsing code in the quaint MySQL connector.
